on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu:latest
    steps:
      - name: Verifica o repositório do Git
        uses: actions/checkout@v2
      - name: Instala node versão 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Istala dependências
        run: npm install
      - name: executa o lint
        run: npx eslint .
